### ISSUE TITLE
Readme contains incorrect information

### ISSUE THREAD

**Issue by mikko-m** [sunng87/hbs#13]
On the readme.md there is mention of set-template-path! function

This function no longer exists:

```
Caused by: java.lang.RuntimeException: No such var: hbs/set-template-path!
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7138)
	at clojure.lang.Compiler.resolve(Compiler.java:7108)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7069)
	at clojure.lang.Compiler.analyze(Compiler.java:6648)
```

edit: it seems that most documentation is incorrect. defhelper does not work as documented, neither does reloading.

Please fix the documentation or at least clearly state that it's obsolete.

**Comment by sunng87** [comment]
Thanks! The doc was updated in ba3de87
